### ISSUE TITLE
Make levels

### ISSUE THREAD

**Issue by SavagePastaMan** [SavagePastaMan/flawless#55]
make a level with these themes
- [x] no guards
- [ ] a guard just sorta patrolling somewhere
- [ ] level with really tight corridors
- [x] two guards right at the exit (it's actually *three*, but 2 was too easy)
- [x] just a door + key and no guards
these will do for now. they should be pretty easy

**Comment by SavagePastaMan** [comment]
i'll do the first one :)

**Comment by EwwPhysics** [comment]
I can try doing the 2nd

**Comment by SavagePastaMan** [comment]
i'll do the fourth

**Comment by SavagePastaMan** [comment]
and the fifth

**Comment by SavagePastaMan** [comment]
:pensive:
